### ISSUE TITLE
Requesting support for iOS 10.0

### ISSUE THREAD

**Issue by Dhana2513** [1Flow-Inc/1flow-ios-sdk#1]
Is there any way to make this SDK available for ios 10.0

**Comment by kai-1flow** [comment]
Hi @Dhana2513 thanks for this request! Our team will evaluate and get back to you. If it is possible, we will support this soon in the next version.

**Comment by kai-1flow** [comment]
@Dhana2513 Good news! We have just released new SDK version with full support for iOS 10.
